config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get "sign_in_with_token", to: "users/sessions#sign_in_with_token"
    # get "email_confirmation", to: "users/sessions#redirect_from_magic_link"
    # post "sign_in_with_token", to: "users/sessions#sign_in_with_token"
  end

  resources :lists do
    resources :items, only: %i[index new edit create update destroy] do
      resource :cross, only: %i[create destroy]
    end
    resources :sharings, only: %i[new create destroy]
  end

  namespace :notifications do
    resource :count, only: :show
  end
  resources :notifications, only: %i[index show]

  resources :sharings, only: :show do
    resource :accept, only: %i[create destroy]
  end

  mount(LetterOpenerWeb::Engine, at: "/letter_opener") if Rails.env.development?

  constraints CanAccessSidekiq do
    mount(Sidekiq::Web, at: "/jobs")
  end

  root to: "lists#index"
end

app/models/list.rb
# frozen_string_literal: true

class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy
  has_many :sharings, dependent: :destroy

  after_save :touch_last_used_at

  # after_create_commit {
  #   broadcast_prepend_to(:lists)
  # }
  # after_update_commit ->(list) {
  #   # broadcast_replace_to(:lists)
  #   broadcast_replace_to(list, :items, template: "lists/items", locals: { list: list })
  # }
  # after_destroy_commit ->(list) {
  #   # broadcast_remove_to(:lists)
  #   broadcast_replace_to(list)
  # }

  def touch_last_used_at
    touch(:last_used_at)
  end
end

app/controllers/lists_controller.rb
# frozen_string_literal: true

class ListsController < ApplicationController
  load_and_authorize_resource :list, param_method: :_list_params

  def index; end

  def show
    @items_uncrossed = @list.items.uncrossed.ordered_for_list
    @items_crossed = @list.items.crossed.ordered_for_list
  end

  def new; end

  def edit; end

  def create
    @list.user = current_user

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(_list_params)
        format.html { redirect_to @list, notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private def _list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/lists_helper.rb
# frozen_string_literal: true

module ListsHelper
  def list_details(list)
    details = ["Last updated #{l(list.last_used_at, format: :short)}"]
    unless list.user == current_user
      details << list.user.email
    end
    details.join(" • ")
  end
end

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>
      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, placeholder: "List name" %>
    <%= form.submit class: "btn" %> or <%= link_to 'cancel', :back %>
<% end %>

app/views/lists/_items.html.erb
<%= turbo_stream_from(list, :items) %>
<div class="mt-4">
  <%= turbo_frame_tag(dom_id(list, :items)) do %>
    <div class="">
      <%= render partial: "items/item_uncrossed", collection: items_uncrossed, as: :item %>
    </div>
    <div class="mt-4">
      <%= render partial: "items/item_crossed", collection: items_crossed, as: :item %>
    </div>
    <% if (items_uncrossed + items_crossed).empty? %>
      <p>
        No items yet
      </p>
    <% end %>
  <% end %>
</div>

app/views/lists/_list.html.erb
<%= link_to list do %>
  <div class="bg-gray-100 mb-4 py-2 px-3">
    <p class="text-gray-500 text-sm">
      <%= list_details(list) %>
    </p>
    <div class="flex justify-between">
      <h2 class="text-2xl align-text-bottom link">
        <%= list.name %>
      </h2>
      <p class="align-text-bottom mt-2 link">
        <%= pluralize(list.items.size, 'items') %>
      </p>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>
<%= turbo_frame_tag(dom_id(@list)) do %>
  <%= render 'form', list: @list %>
  <div class="mt-5">
    <%= link_to 'Share your list with someone', new_list_sharing_path(@list), class: "btn", target: "_top" %>
  </div>
<% end %>

app/views/lists/index.html.erb
<div class="flex justify-between align-top">
  <h1 class="text-3xl">
    Your lists
  </h1>
  <%= link_to new_list_path, class: "link" do %>
    <i class="fas fa-plus mt-1 mr-1 text-lg"></i>
  <% end %>
</div>
<div class="mt-4">
  <%= render @lists %>
  <% if @lists.empty? %>
    <p>
      No lists yet
    </p>
  <% end %>
</div>

app/views/lists/new.html.erb
<%= render 'form', list: @list %>

app/views/lists/show.html.erb
<%= turbo_stream_from(@list) %>
<%= turbo_frame_tag(dom_id(@list)) do %>
  <div class="flex justify-between">
    <h1 class="text-3xl">
      <%= @list.name %>
    </h1>
    <%= link_to edit_list_path(@list), class: "link" do %>
      <i class="fas fa-cog mt-1 mr-1 text-lg"></i>
    <% end %>
  </div>

  <%= render "items/form", item: Item.new(list: @list) %>
  <%= render "items", list: @list, items_uncrossed: @items_uncrossed, items_crossed: @items_crossed %>
<% end %>