config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get "sign_in_with_token", to: "users/sessions#sign_in_with_token"
    # get "email_confirmation", to: "users/sessions#redirect_from_magic_link"
    # post "sign_in_with_token", to: "users/sessions#sign_in_with_token"
  end

  resources :lists do
    resources :items, only: %i[index new edit create update destroy] do
      resource :cross, only: %i[create destroy]
    end
    resources :sharings, only: %i[new create destroy]
  end

  namespace :notifications do
    resource :count, only: :show
  end
  resources :notifications, only: %i[index show]

  resources :sharings, only: :show do
    resource :accept, only: %i[create destroy]
  end

  mount(LetterOpenerWeb::Engine, at: "/letter_opener") if Rails.env.development?

  constraints CanAccessSidekiq do
    mount(Sidekiq::Web, at: "/jobs")
  end

  root to: "lists#index"
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  include ActionView::RecordIdentifier
  belongs_to :list

  validates :name, presence: true

  after_commit :_touch_list_last_used_at, :_stream_to_list

  scope :crossed, -> { where.not(crossed_at: nil) }
  scope :uncrossed, -> { where(crossed_at: nil) }
  scope :ordered_for_list, -> { order(crossed_at: :desc, created_at: :desc) }

  def crossed?
    crossed_at
  end

  def cross!
    update(crossed_at: Time.current)
  end

  def uncross!
    update(crossed_at: nil)
  end

  private def _touch_list_last_used_at
    list.touch_last_used_at
  end

  private def _stream_to_list
    broadcast_replace_to(list, :items, target: dom_id(list, :items),
                                       partial: "lists/items",
                                       locals: { list: list,
                                                 items_uncrossed: list.items.uncrossed.ordered_for_list,
                                                 items_crossed: list.items.crossed.ordered_for_list })
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  load_and_authorize_resource :list
  load_and_authorize_resource :item, through: :list, param_method: :_item_params

  def index
    @items_uncrossed = @items.uncrossed.ordered_for_list
    @items_crossed = @items.crossed.ordered_for_list
  end

  def show; end

  def new; end

  def edit; end

  def create
    respond_to do |format|
      if @item.save
        format.html { redirect_to list_path(@list), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: list_item_path(@list, @item) }
      else
        format.turbo_stream {
          render turbo_stream: turbo_stream.replace(
            @item,
            partial: "items/form",
            locals: { item: @item }
          )
        }
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to list_item_path(@list, @item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: list_item_path(@list, @item) }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to list_path(@list), notice: "Item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private def item_params
    params.require(:item).permit(:name, :crossed_at, :list_id)
  end
end

app/views/items/_form.html.erb
<%= form_with(model: [item.list, item], id: dom_id(item), class: "mt-4") do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, placeholder: "Item name" %>
    <%= form.submit class: "btn" %> or <%= link_to 'cancel', item.list, class: "link" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= turbo_frame_tag(dom_id(item)) do %>
  <div class="flex justify-between">
    <%= link_to item.name, list_item_cross_path(item.list, item), data: { method: (item.crossed? ? :delete : :post) }, class: (item.crossed? ? "line-through" : nil) %>
    <div>
      <%= link_to edit_list_item_path(item.list, item) do %>
        <i class="fas fa-cog mt-1 mr-1"></i>
      <% end %>
      <%= link_to list_item_path(item.list, item), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash mt-1 mr-1"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/_item_crossed.html.erb
<%= turbo_frame_tag(dom_id(item)) do %>
  <div class="flex justify-between my-1 py-1 px-2 text-gray-400">
    <%= link_to item.name, list_item_cross_path(item.list, item), data: { method: (item.crossed? ? :delete : :post) }, class: (item.crossed? ? "line-through" : nil) %>
    <div>
      <%= link_to edit_list_item_path(item.list, item) do %>
        <i class="fas fa-cog mt-1 mr-1"></i>
      <% end %>
      <%= link_to list_item_path(item.list, item), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash mt-1 mr-1"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/_item_uncrossed.html.erb
<%= turbo_frame_tag(dom_id(item)) do %>
  <div class="flex justify-between bg-gray-100 my-1 py-1 px-2">
    <%= link_to item.name, list_item_cross_path(item.list, item), data: { method: (item.crossed? ? :delete : :post) }, class: (item.crossed? ? "line-through" : nil) %>
    <div>
      <%= link_to edit_list_item_path(item.list, item), class: "link" do %>
        <i class="fas fa-cog mt-1 mr-1"></i>
      <% end %>
      <%= link_to list_item_path(item.list, item), method: :delete, data: { confirm: 'Are you sure?' }, class: "link" do %>
        <i class="fas fa-trash mt-1 mr-1"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>
<%= turbo_frame_tag(dom_id(@item)) do %>
  <%= render 'form', item: @item %>
<% end %>

<%= link_to 'Back', list_items_path(@item.list), target: :_top %>

app/views/items/index.html.erb
<%= turbo_frame_tag(dom_id(@list, :items)) do %>
  <%= render @items %>
  <% if @items.empty? %>
    <p>
      No items yet
    </p>
  <% end %>
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

app/views/items/show.html.erb
<%= render @item %>