config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }

  devise_scope :user do
    get "sign_in_with_token", to: "users/sessions#sign_in_with_token"
    # get "email_confirmation", to: "users/sessions#redirect_from_magic_link"
    # post "sign_in_with_token", to: "users/sessions#sign_in_with_token"
  end

  resources :lists do
    resources :items, only: %i[index new edit create update destroy] do
      resource :cross, only: %i[create destroy]
    end
    resources :sharings, only: %i[new create destroy]
  end

  namespace :notifications do
    resource :count, only: :show
  end
  resources :notifications, only: %i[index show]

  resources :sharings, only: :show do
    resource :accept, only: %i[create destroy]
  end

  mount(LetterOpenerWeb::Engine, at: "/letter_opener") if Rails.env.development?

  constraints CanAccessSidekiq do
    mount(Sidekiq::Web, at: "/jobs")
  end

  root to: "lists#index"
end

app/views/layouts/_flash.html.erb
<%= turbo_frame_tag "flash" do %>
  <%- flash.each do |key, value| %>
    <%-
      if value.present?
        fclass = ['alert']
    %>
      <div class="<%= fclass.flatten.uniq.compact.join(" ") %>" role="alert">
        <div class="container">
          <%= value %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<header class="mb-6" data-controller="navigation">
  <div class="flex items-center justify-between py-3">
    <div id="branding">
      <i class="far fa-list-alt mt-1 mr-1 text-lg"></i>
      <%= link_to "ListIt", root_path, class: "flex-auto font-mono text-lg font mt-1" %>
    </div>
    <% if user_signed_in? %>
      <div class="flex items-center justify-between">
        <%= render "layouts/notifications" %>
        <button class="block focus:outline-none" data-action="click->navigation#toggleMenu">
          <svg class="h-6 w-6 fill-current" viewBox="0 0 24 24">
            <path data-navigation-target="iconClose" fill-rule="evenodd" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/>
            <path data-navigation-target="iconOpen" class="hidden" fill-rule="evenodd" d="M18.278 16.864a1 1 0 0 1-1.414 1.414l-4.829-4.828-4.828 4.828a1 1 0 0 1-1.414-1.414l4.828-4.829-4.828-4.828a1 1 0 0 1 1.414-1.414l4.829 4.828 4.828-4.828a1 1 0 1 1 1.414 1.414l-4.828 4.829 4.828 4.828z"/>
          </svg>
        </button>
      </div>
    <% end %>
  </div>
  <% if user_signed_in? %>
    <div class="pb-6 text-right hidden" data-navigation-target="menu">
      <%= link_to "Lists", lists_path, class: "block py-1" %>
      <%= link_to "Sharings", "#", class: "block py-1" %>
      <%= link_to "Français", { locale: :fr }, class: "block py-1" %>
      <% if user_signed_in? %>
        <p class="block py-5 text-gray-600">
          Signed in as <%= current_user.email %> |
          <%= link_to('Log Out', destroy_user_session_path, method: 'delete', class: "dropdown-item", target: :_top) %>
        </p>
      <% end %>
    </div>
  <% end %>
</header>

app/views/layouts/_notifications.html.erb
<%= turbo_stream_from(current_user, :notifications_count) %>
<%= turbo_frame_tag(dom_id(current_user, :notifications_count), src: notifications_count_path) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsapps</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= yield :head %>
    <%= turbo_include_tags %>
    <%= stimulus_include_tags %>
  </head>

  <body>
    <div class="container mx-auto px-4">
      <%= render "layouts/navigation" %>
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
  </body>
</html>